name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Deploy Laravel
        run: |
          cd /var/www/html/admin-panel

          git fetch origin
          git reset --hard origin/main

          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

          npm ci
          npm run build

          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          php artisan storage:link || true

          sudo chown -R akmal:www-data /var/www/html/admin-panel
          sudo chmod -R 775 /var/www/html/admin-panel/storage
          sudo chmod -R 775 /var/www/html/admin-panel/bootstrap/cache
