name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ["self-hosted","linux","x64","production"]

    steps:
      - name: Deploy locally
        run: |
          set -e

          cd /var/www/html/admin-panel

          echo "Fixing git safe directory..."
          git config --global --add safe.directory /var/www/html/admin-panel

          echo "Pulling latest code..."
          git pull origin main

          echo "Installing dependencies..."
          composer install --no-interaction --prefer-dist --optimize-autoloader

          echo "Running migrations..."
          php artisan migrate --force

          echo "Clearing cache..."
          php artisan optimize:clear

          echo "Restarting queue..."
          php artisan queue:restart